dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
env:
  -
  - SOLC_NIGHTLY=true
  # - SOLIDITY_COVERAGE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLC_NIGHTLY=true
    # - env: SOLIDITY_COVERAGE=true
before_script:
  - truffle version
script:
  - bash ./bin/test.sh
